server:
  port: 1111

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ingress_group_db
    username: postgres
    password: ingress

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
