version: '3.8'

services:
  postgres:
    container_name: ingress_group
    image: postgres:latest
    environment:
      POSTGRES_DB: ingress_group_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ingress
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: